import type { ActivityDefinition } from "./types";

export const ACTIVITIES: ActivityDefinition[] = [
  {
    id: "study",
    label: "Study",
    description: "Focus on schoolwork and discipline.",
    icon: "📘",
    cost: 1,
    effects: { stats: { education: 8, stress: 2, happiness: -1 } },
    goalIds: ["graduate_high_school", "get_into_university"],
    hint: "Education and discipline improve your chances at university.",
  },
  {
    id: "exercise",
    label: "Exercise",
    description: "Train your body and keep your routine steady.",
    icon: "🏃",
    cost: 1,
    effects: { stats: { health: 6, happiness: 3, stress: -3 } },
    goalIds: ["build_fitness"],
    hint: "Fitness grows through repeated effort.",
  },
  {
    id: "work",
    label: "Work part time",
    description: "Take on a few paid hours and build your track record.",
    icon: "💼",
    cost: 1,
    effects: { stats: { cash: 18, money: 18, income: 6, reputation: 2, stress: 3 } },
    goalIds: ["get_promoted", "save_emergency_fund"],
    hint: "Work sharpens your reputation and your cash cushion.",
  },
  {
    id: "rest",
    label: "Rest",
    description: "Recover from the week and reduce strain.",
    icon: "🛋️",
    cost: 1,
    effects: { stats: { stress: -10, health: 4, happiness: 3 } },
    goalIds: ["build_fitness"],
    hint: "Rest shields your health from burnout.",
  },
  {
    id: "read",
    label: "Read",
    description: "Spend the evening learning something new.",
    icon: "📖",
    cost: 1,
    effects: { stats: { education: 4, skill: 3, happiness: 2, stress: -1 } },
    goalIds: ["learn_programming", "graduate_high_school"],
    hint: "Reading broadens your mind and your skill.",
  },
  {
    id: "program",
    label: "Learn programming",
    description: "Build real software skills with focused practice.",
    icon: "💻",
    cost: 1,
    effects: { stats: { skill: 10, education: 4, happiness: 2 } },
    goalIds: ["learn_programming"],
    hint: "Programming progress compounds when you keep showing up.",
  },
  {
    id: "music",
    label: "Practice music",
    description: "Sharpen your craft and lift your confidence.",
    icon: "🎵",
    cost: 1,
    effects: { stats: { skill: 6, happiness: 3, stress: -1 } },
    goalIds: ["build_social_circle"],
    hint: "Music strengthens confidence and makes you memorable.",
  },
  {
    id: "family",
    label: "Call family",
    description: "Reach out and keep your support network warm.",
    icon: "📞",
    cost: 1,
    effects: { stats: { relationships: 6, happiness: 2, stress: -2 } },
    goalIds: ["build_social_circle"],
    hint: "Close relationships become a reliable foundation.",
  },
  {
    id: "friends",
    label: "Meet friends",
    description: "Spend time with people who make life feel lighter.",
    icon: "🫶",
    cost: 1,
    effects: { stats: { relationships: 5, happiness: 4, stress: -2 } },
    goalIds: ["build_social_circle"],
    hint: "Friendships become easier to keep when you invest in them.",
  },
  {
    id: "volunteer",
    label: "Volunteer",
    description: "Give your time to something larger than yourself.",
    icon: "🤝",
    cost: 1,
    effects: { stats: { reputation: 4, happiness: 3, relationships: 3 } },
    goalIds: ["build_social_circle"],
    hint: "Service grows your reputation and your sense of purpose.",
  },
];
